version: "3.7"

services:
  blabber:
    image: dinardov/blabber:latest
    command: npm run dev
    working_dir: /blabber
    volumes: 
      - ./:/blabber
    ports: 
      - 3000:3000
    labels:
      - "traefik.frontend.rule=Host:blabber.docker.localhost"
      - "traefik.frontend.rule=ReplacePathRegex: ^/api/blabs(?:/(.*))?$$ /blabs/$${1}"
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
  client-ui:
    image: vtcs2304s19/blabber-client